//User interface
export interface User {
  id?: number;
  firstName: string;
  lastName: string;
  email?: string;
  birthDate?: string;
  phoneNumber?: string;
}


export const users: User[] = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    email: "john.doe@example.com",
    birthDate: "1990-01-15",
    phoneNumber: "123-456-7890",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    email: "jane.smith@example.com",
    birthDate: "1985-07-20",
    phoneNumber: "234-567-8901",
  },
  {
    id: 3,
    firstName: "James",
    lastName: "Johnson",
    email: "james.johnson@example.com",
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Williams",
    email: "emily.williams@example.com",
    birthDate: "1992-03-12",
  },
  {
    id: 5,
    firstName: "Michael",
    lastName: "Brown",
    email: "michael.brown@example.com",
    phoneNumber: "345-678-9012",
  },
  {
    id: 6,
    firstName: "Jessica",
    lastName: "Jones",
    email: "jessica.jones@example.com",
    birthDate: "1988-11-05",
    phoneNumber: "456-789-0123",
  },
  {
    id: 7,
    firstName: "David",
    lastName: "Garcia",
    email: "david.garcia@example.com",
    birthDate: "1995-04-30",
  },
  {
    id: 8,
    firstName: "Sarah",
    lastName: "Martinez",
    email: "sarah.martinez@example.com",
  },
  {
    id: 9,
    firstName: "Daniel",
    lastName: "Rodriguez",
    email: "daniel.rodriguez@example.com",
    phoneNumber: "567-890-1234",
  },
  {
    id: 10,
    firstName: "Sophia",
    lastName: "Lopez",
    email: "sophia.lopez@example.com",
    birthDate: "1993-09-19",
  },
  {
    id: 11,
    firstName: "Anthony",
    lastName: "Gonzalez",
    email: "anthony.gonzalez@example.com",
    birthDate: "1987-06-14",
    phoneNumber: "678-901-2345",
  },
  {
    id: 12,
    firstName: "Olivia",
    lastName: "Wilson",
    email: "olivia.wilson@example.com",
  },
  {
    id: 13,
    firstName: "Joshua",
    lastName: "Anderson",
    email: "joshua.anderson@example.com",
    birthDate: "1991-12-22",
  },
  {
    id: 14,
    firstName: "Emma",
    lastName: "Thomas",
    email: "emma.thomas@example.com",
    phoneNumber: "789-012-3456",
  },
  {
    id: 15,
    firstName: "Christopher",
    lastName: "Taylor",
    email: "christopher.taylor@example.com",
    birthDate: "1994-08-03",
    phoneNumber: "890-123-4567",
  },
  {
    id: 16,
    firstName: "Elizabeth",
    lastName: "Moore",
    email: "elizabeth.moore@example.com",
    phoneNumber: "901-234-5678",
  },
  {
    id: 17,
    firstName: "Andrew",
    lastName: "Jackson",
    email: "andrew.jackson@example.com",
    birthDate: "1989-05-17",
  },
  {
    id: 18,
    firstName: "Isabella",
    lastName: "White",
    email: "isabella.white@example.com",
  },
  {
    id: 19,
    firstName: "Matthew",
    lastName: "Harris",
    email: "matthew.harris@example.com",
    birthDate: "1996-02-25",
    phoneNumber: "012-345-6789",
  },
  {
    id: 20,
    firstName: "Mia",
    lastName: "Martin",
    email: "mia.martin@example.com",
    birthDate: "1986-10-30",
  },
  {
    id: 21,
    firstName: "Alexander",
    lastName: "Martinez",
    email: "alexander.martinez@example.com",
  },
  {
    id: 22,
    firstName: "Amelia",
    lastName: "Clark",
    email: "amelia.clark@example.com",
    phoneNumber: "123-456-7890",
  },
  {
    id: 23,
    firstName: "Ethan",
    lastName: "Lewis",
    email: "ethan.lewis@example.com",
    birthDate: "1997-03-13",
  },
  {
    id: 24,
    firstName: "Ava",
    lastName: "Robinson",
    email: "ava.robinson@example.com",
    birthDate: "1990-08-08",
    phoneNumber: "234-567-8901",
  },
  {
    id: 25,
    firstName: "Mason",
    lastName: "Walker",
    email: "mason.walker@example.com",
    phoneNumber: "345-678-9012",
  },
  {
    id: 26,
    firstName: "Harper",
    lastName: "Young",
    email: "harper.young@example.com",
  },
  {
    id: 27,
    firstName: "Logan",
    lastName: "Allen",
    email: "logan.allen@example.com",
    birthDate: "1992-04-11",
  },
  {
    id: 28,
    firstName: "Abigail",
    lastName: "King",
    email: "abigail.king@example.com",
    phoneNumber: "456-789-0123",
  },
  {
    id: 29,
    firstName: "Jacob",
    lastName: "Scott",
    email: "jacob.scott@example.com",
  },
  {
    id: 30,
    firstName: "Ella",
    lastName: "Green",
    email: "ella.green@example.com",
    birthDate: "1991-01-02",
  },
  {
    id: 31,
    firstName: "Ryan",
    lastName: "Baker",
    email: "ryan.baker@example.com",
    phoneNumber: "567-890-1234",
  },
  {
    id: 32,
    firstName: "Emily",
    lastName: "Adams",
    email: "emily.adams@example.com",
    birthDate: "1988-07-24",
  },
  {
    id: 33,
    firstName: "William",
    lastName: "Nelson",
    email: "william.nelson@example.com",
    phoneNumber: "678-901-2345",
  },
  {
    id: 34,
    firstName: "Charlotte",
    lastName: "Carter",
    email: "charlotte.carter@example.com",
  },
  {
    id: 35,
    firstName: "Benjamin",
    lastName: "Mitchell",
    email: "benjamin.mitchell@example.com",
    birthDate: "1993-05-29",
  },
  {
    id: 36,
    firstName: "Sofia",
    lastName: "Perez",
    email: "sofia.perez@example.com",
    birthDate: "1987-12-12",
    phoneNumber: "789-012-3456",
  },
  {
    id: 37,
    firstName: "Henry",
    lastName: "Roberts",
    email: "henry.roberts@example.com",
  },
  {
    id: 38,
    firstName: "Aria",
    lastName: "Turner",
    email: "aria.turner@example.com",
    phoneNumber: "890-123-4567",
  },
  {
    id: 39,
    firstName: "Jackson",
    lastName: "Phillips",
    email: "jackson.phillips@example.com",
    birthDate: "1995-09-14",
  },
  {
    id: 40,
    firstName: "Grace",
    lastName: "Campbell",
    email: "grace.campbell@example.com",
    phoneNumber: "901-234-5678",
  },
  {
    id: 41,
    firstName: "Sebastian",
    lastName: "Parker",
    email: "sebastian.parker@example.com",
    birthDate: "1989-03-27",
  },
  {
    id: 42,
    firstName: "Victoria",
    lastName: "Evans",
    email: "victoria.evans@example.com",
  },
  {
    id: 43,
    firstName: "Aiden",
    lastName: "Edwards",
    email: "aiden.edwards@example.com",
    birthDate: "1996-06-18",
  },
  {
    id: 44,
    firstName: "Chloe",
    lastName: "Collins",
    email: "chloe.collins@example.com",
    phoneNumber: "012-345-6789",
  },
  {
    id: 45,
    firstName: "Lucas",
    lastName: "Stewart",
    email: "lucas.stewart@example.com",
    birthDate: "1991-10-21",
  },
  {
    id: 46,
    firstName: "Penelope",
    lastName: "Sanchez",
    email: "penelope.sanchez@example.com",
  },
  {
    id: 47,
    firstName: "Nathan",
    lastName: "Morris",
    email: "nathan.morris@example.com",
    birthDate: "1985-02-14",
    phoneNumber: "123-456-7890",
  },
  {
    id: 48,
    firstName: "Zoe",
    lastName: "Reed",
    email: "zoe.reed@example.com",
    phoneNumber: "234-567-8901",
  },
  {
    id: 49,
    firstName: "Jack",
    lastName: "Cook",
    email: "jack.cook@example.com",
    birthDate: "1992-12-25",
  },
  {
    id: 50,
    firstName: "Layla",
    lastName: "Bell",
    email: "layla.bell@example.com",
  },
  {
    id: 51,
    firstName: "Owen",
    lastName: "Murphy",
    email: "owen.murphy@example.com",
  },
  {
    id: 52,
    firstName: "Lily",
    lastName: "Bailey",
    email: "lily.bailey@example.com",
    birthDate: "1988-11-10",
  },
  {
    id: 53,
    firstName: "Levi",
    lastName: "Rivera",
    email: "levi.rivera@example.com",
    phoneNumber: "345-678-9012",
  },
  {
    id: 54,
    firstName: "Eleanor",
    lastName: "Cooper",
    email: "eleanor.cooper@example.com",
    birthDate: "1990-05-18",
  },
  {
    id: 55,
    firstName: "Dylan",
    lastName: "Richardson",
    email: "dylan.richardson@example.com",
  },
  {
    id: 56,
    firstName: "Hannah",
    lastName: "Cox",
    email: "hannah.cox@example.com",
    birthDate: "1993-07-23",
    phoneNumber: "456-789-0123",
  },
  {
    id: 57,
    firstName: "Isaac",
    lastName: "Howard",
    email: "isaac.howard@example.com",
    birthDate: "1987-04-05",
  },
  {
    id: 58,
    firstName: "Scarlett",
    lastName: "Ward",
    email: "scarlett.ward@example.com",
    phoneNumber: "567-890-1234",
  },
  {
    id: 59,
    firstName: "Gabriel",
    lastName: "Torres",
    email: "gabriel.torres@example.com",
  },
  {
    id: 60,
    firstName: "Ellie",
    lastName: "Peterson",
    email: "ellie.peterson@example.com",
    birthDate: "1991-09-30",
    phoneNumber: "678-901-2345",
  },
  {
    id: 61,
    firstName: "Caleb",
    lastName: "Gray",
    email: "caleb.gray@example.com",
    phoneNumber: "789-012-3456",
  },
  {
    id: 62,
    firstName: "Nora",
    lastName: "Ramirez",
    email: "nora.ramirez@example.com",
  },
  {
    id: 63,
    firstName: "Luke",
    lastName: "James",
    email: "luke.james@example.com",
    birthDate: "1994-11-09",
  },
  {
    id: 64,
    firstName: "Aubrey",
    lastName: "Watson",
    email: "aubrey.watson@example.com",
    phoneNumber: "890-123-4567",
  },
  {
    id: 65,
    firstName: "Wyatt",
    lastName: "Brooks",
    email: "wyatt.brooks@example.com",
  },
  {
    id: 66,
    firstName: "Addison",
    lastName: "Kelly",
    email: "addison.kelly@example.com",
    birthDate: "1992-02-26",
  },
  {
    id: 67,
    firstName: "Jayden",
    lastName: "Sanders",
    email: "jayden.sanders@example.com",
  },
  {
    id: 68,
    firstName: "Luna",
    lastName: "Price",
    email: "luna.price@example.com",
    phoneNumber: "901-234-5678",
  },
  {
    id: 69,
    firstName: "Elijah",
    lastName: "Bennett",
    email: "elijah.bennett@example.com",
    birthDate: "1989-06-19",
  },
  {
    id: 70,
    firstName: "Camila",
    lastName: "Wood",
    email: "camila.wood@example.com",
  },
  {
    id: 71,
    firstName: "Michael",
    lastName: "Barnes",
    email: "michael.barnes@example.com",
    birthDate: "1995-03-14",
    phoneNumber: "012-345-6789",
  },
  {
    id: 72,
    firstName: "Samantha",
    lastName: "Ross",
    email: "samantha.ross@example.com",
    phoneNumber: "123-456-7890",
  },
  {
    id: 73,
    firstName: "Joseph",
    lastName: "Henderson",
    email: "joseph.henderson@example.com",
  },
  {
    id: 74,
    firstName: "Avery",
    lastName: "Coleman",
    email: "avery.coleman@example.com",
    birthDate: "1990-10-08",
    phoneNumber: "234-567-8901",
  },
  {
    id: 75,
    firstName: "Samuel",
    lastName: "Jenkins",
    email: "samuel.jenkins@example.com",
    birthDate: "1985-01-30",
  },
  {
    id: 76,
    firstName: "Evelyn",
    lastName: "Perry",
    email: "evelyn.perry@example.com",
    birthDate: "1993-05-02",
  },
  {
    id: 77,
    firstName: "Liam",
    lastName: "Powell",
    email: "liam.powell@example.com",
    phoneNumber: "345-678-9012",
  },
  {
    id: 78,
    firstName: "Zoey",
    lastName: "Long",
    email: "zoey.long@example.com",
    birthDate: "1992-12-16",
  },
  {
    id: 79,
    firstName: "Noah",
    lastName: "Patterson",
    email: "noah.patterson@example.com",
  },
  {
    id: 80,
    firstName: "Aiden",
    lastName: "Hughes",
    email: "aiden.hughes@example.com",
    birthDate: "1997-08-29",
    phoneNumber: "456-789-0123",
  },
  {
    id: 81,
    firstName: "Layla",
    lastName: "Flores",
    email: "layla.flores@example.com",
  },
  {
    id: 82,
    firstName: "Daniel",
    lastName: "Washington",
    email: "daniel.washington@example.com",
    birthDate: "1991-06-25",
  },
  {
    id: 83,
    firstName: "Harper",
    lastName: "Butler",
    email: "harper.butler@example.com",
    phoneNumber: "567-890-1234",
  },
  {
    id: 84,
    firstName: "Isaac",
    lastName: "Simmons",
    email: "isaac.simmons@example.com",
    birthDate: "1995-04-10",
    phoneNumber: "678-901-2345",
  },
  {
    id: 85,
    firstName: "Eleanor",
    lastName: "Foster",
    email: "eleanor.foster@example.com",
    birthDate: "1988-09-01",
  },
  {
    id: 86,
    firstName: "Gabriel",
    lastName: "Gonzalez",
    email: "gabriel.gonzalez@example.com",
  },
  {
    id: 87,
    firstName: "Mason",
    lastName: "Bryant",
    email: "mason.bryant@example.com",
    phoneNumber: "789-012-3456",
  },
  {
    id: 88,
    firstName: "Charlotte",
    lastName: "Alexander",
    email: "charlotte.alexander@example.com",
    birthDate: "1994-03-05",
  },
  {
    id: 89,
    firstName: "Logan",
    lastName: "Russell",
    email: "logan.russell@example.com",
  },
  {
    id: 90,
    firstName: "Sofia",
    lastName: "Griffin",
    email: "sofia.griffin@example.com",
    birthDate: "1990-07-20",
    phoneNumber: "890-123-4567",
  },
  {
    id: 91,
    firstName: "Lucas",
    lastName: "Hayes",
    email: "lucas.hayes@example.com",
    birthDate: "1996-12-28",
  },
  {
    id: 92,
    firstName: "Isabella",
    lastName: "Myers",
    email: "isabella.myers@example.com",
    phoneNumber: "901-234-5678",
  },
  {
    id: 93,
    firstName: "Ethan",
    lastName: "Ford",
    email: "ethan.ford@example.com",
    birthDate: "1987-10-06",
  },
  {
    id: 94,
    firstName: "Amelia",
    lastName: "Hamilton",
    email: "amelia.hamilton@example.com",
    phoneNumber: "012-345-6789",
  },
  {
    id: 95,
    firstName: "Wyatt",
    lastName: "Graham",
    email: "wyatt.graham@example.com",
    birthDate: "1993-08-22",
  },
  {
    id: 96,
    firstName: "Ava",
    lastName: "Sullivan",
    email: "ava.sullivan@example.com",
    birthDate: "1986-05-09",
  },
  {
    id: 97,
    firstName: "Sebastian",
    lastName: "Mason",
    email: "sebastian.mason@example.com",
  },
  {
    id: 98,
    firstName: "Mia",
    lastName: "Fisher",
    email: "mia.fisher@example.com",
    birthDate: "1992-11-17",
    phoneNumber: "123-456-7890",
  },
  {
    id: 99,
    firstName: "Liam",
    lastName: "Hunter",
    email: "liam.hunter@example.com",
    phoneNumber: "234-567-8901",
  },
  {
    id: 100,
    firstName: "Emily",
    lastName: "Harrison",
    email: "emily.harrison@example.com",
    birthDate: "1990-02-14",
  },
];
